pipelines:
  default:
    - parallel:
      - step:
          name: Test on Node v4
          image: node:4.9.1
          caches:
            - node
          script:
            - npm install
            - npm test
      - step:
          name: Test on Node v6
          image: node:6.14.1
          caches:
            - node
          script:
            - npm install
            - npm test
      - step:
          name: Test on Node v8
          image: node:8.11.1
          caches:
            - node
          script:
            - npm install
            - npm test
